/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kadhxcxuhtuwftytcktj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZGh4Y3h1aHR1d2Z0eXRja3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxNjQ2MTMsImV4cCI6MjA5NTc0MDYxM30.CE6h7tKJIrXopGzr3ZtcN-0IiR-PprcPborvShTccHA"